### PR TITLE
Fix TypeScript compilation

### PR DESCRIPTION
**Pull request by ValentinMouret**
I was having issues building my company’s project using this library.
These changes make our project compile, so they might be useful to
someone else.

Thanks a lot for the library, by the way, it’s very useful!

### CODE REVIEW

**Comment by amz-tools** [comment]
Hi @ValentinMouret,

sorry for the late reply. We'll have a look at it soon and see if we can merge it into our next release.

**Comment by TraceM171** [comment]
I am getting a runtime error with this modifications:
TypeError: amazon_sp_api_1.default is not a constructor

**Comment by Cellis9421** [comment]
I was having the same typescript definition build issues and this PR fixed the issue. Thank you! Hope to see this merged into main soon.

**Comment by amz-tools** [comment]
Hi @ValentinMouret,

we finally merged your PR, it will be part of the next version. Just to complete this topic, another fix for the issue you experienced would have been to add `"skipLibCheck": true` to your tsconfig.json.

@TraceM171, regarding your issue with this PR, could you have a look at stackoverflow:
https://stackoverflow.com/questions/42652423/error-default-is-not-a-constructor

**Comment by TraceM171** [comment]
Hi,

thanks for the link, but the import is correct as there are no compile time errors, I tried using the latest version of this library v0.7.10, but the error persists.

For reference, without changing any code from the library using the version mentioned above, the import is:
`import SellingPartner from "amazon-sp-api";`

**Comment by kri5t** [comment]
Yes I'm having the same issues. Can you please fix this. I don't consider `"skipLibCheck": true` a fix for this.

**Pull request merged**
